name: Linmo CI (GNU Only)

on:
    push:
        branches: [main, ci]
    pull_request:
        branches: [main, ci]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential qemu-system-riscv32 wget

            - name: Download RISC-V GNU Toolchain
              run: |
                  wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2025.06.13/riscv32-elf-ubuntu-22.04-gcc-nightly-2025.06.13-nightly.tar.xz
                  tar -xf riscv32-elf-ubuntu-22.04-gcc-nightly-2025.06.13-nightly.tar.xz
                  echo "$PWD/riscv/bin" >> $GITHUB_PATH

            - name: Verify toolchain installation
              run: |
                  riscv32-unknown-elf-gcc --version
                  qemu-system-riscv32 --version
              env:
                  CROSS_COMPILE: riscv32-unknown-elf-

            - name: Build Linmo kernel
              run: |
                  make clean
                  make
              env:
                  CROSS_COMPILE: riscv32-unknown-elf-

            - name: Build and run cpubench
              run: |
                  make clean
                  make cpubench
                  timeout 5s qemu-system-riscv32 -nographic -machine virt -bios none -kernel build/image.elf || true
                  echo "cpubench completed"
              env:
                  CROSS_COMPILE: riscv32-unknown-elf-
